# Config file for automatic testing at travis-ci.org
dist: bionic
sudo: required
language: python
python:
  - 3.8
  - 3.7
  - 3.6

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh && bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - pip install -U tox-travis tox-conda
  - curl -OL https://osf.io/5jzre/download > tests/test-data/Pfam-A.hmm.h3f
  - curl -OL https://osf.io/s6xtb/download > tests/test-data/Pfam-A.hmm.h3i
  - curl -OL https://osf.io/2jnas/download > tests/test-data/Pfam-A.hmm.h3m
  - curl -OL https://osf.io/8yt9r/download > tests/test-data/Pfam-A.hmm.h3p

# Command to run tests, e.g. python setup.py test
script: tox

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: camillescott
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: camillescott/fuckitall
    python: 3.8
